services:
  db:
    image: postgres:16-alpine
    container_name: polyfestival_back_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: polyfestival
      POSTGRES_PASSWORD: polyfestival
      POSTGRES_DB: polyfestival
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - polyfestival_back_network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - polyfestival_back_network

volumes:
  db_data:

networks:
  polyfestival_back_network:
    driver: bridge