name: deploy-PolyFestival-Back-Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: 
      labels: [self-hosted, lovelace-festival-back]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env File
        run: |
          touch .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASEURL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT_PROD }}" >> .env
      
      - name: Down Existing Containers
        run: |
          docker compose -f docker-compose-dev.yml down

        # run: |
        #   cd /home/github-runner/polyfestival/prod/polyfestival.back 
        #   docker compose -f docker-compose.prod.yml down
        #   git pull
        #   docker-compose -p prod -f docker-compose-prod.yml up -d